### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by neiromancer** [kberov/Ado#92]
$ cpanm DBIx::Simple::Class
--> Working on DBIx::Simple::Class
Fetching http://www.cpan.org/authors/id/B/BE/BEROV/DBIx-Simple-Class-1.008.tar.gz ... OK
Configuring DBIx-Simple-Class-1.008 ... OK
Building and testing DBIx-Simple-Class-1.008 ... OK
Successfully installed DBIx-Simple-Class-1.008
1 distribution installed

$ cpanm Mojolicious::Plugin::DSC
--> Working on Mojolicious::Plugin::DSC
Fetching http://www.cpan.org/authors/id/B/BE/BEROV/Mojolicious-Plugin-DSC-1.004.tar.gz ... OK
Configuring Mojolicious-Plugin-DSC-1.004 ... OK
==> Found dependencies: DBIx::Simple::Class
--> Working on DBIx::Simple::Class
Fetching http://www.cpan.org/authors/id/B/BE/BEROV/DBIx-Simple-Class-1.008.tar.gz ... OK
Configuring DBIx-Simple-Class-1.008 ... OK
Building and testing DBIx-Simple-Class-1.008 ... OK
Successfully installed DBIx-Simple-Class-1.008
! Installing the dependencies failed: Module 'DBIx::Simple::Class' is not installed
! Bailing out the installation for Mojolicious-Plugin-DSC-1.004.
1 distribution installed

$ cpanm Ado
--> Working on Ado
Fetching http://www.cpan.org/authors/id/B/BE/BEROV/Ado-0.83.tar.gz ... OK
Configuring Ado-0.83 ... OK
==> Found dependencies: Mojolicious::Plugin::DSC, DBIx::Simple::Class
--> Working on Mojolicious::Plugin::DSC
Fetching http://www.cpan.org/authors/id/B/BE/BEROV/Mojolicious-Plugin-DSC-1.004.tar.gz ... OK
Configuring Mojolicious-Plugin-DSC-1.004 ... OK
==> Found dependencies: DBIx::Simple::Class
--> Working on DBIx::Simple::Class
Fetching http://www.cpan.org/authors/id/B/BE/BEROV/DBIx-Simple-Class-1.008.tar.gz ... OK
Configuring DBIx-Simple-Class-1.008 ... OK
Building and testing DBIx-Simple-Class-1.008 ... OK
Successfully installed DBIx-Simple-Class-1.008
! Installing the dependencies failed: Module 'DBIx::Simple::Class' is not installed
! Bailing out the installation for Mojolicious-Plugin-DSC-1.004.
! Installing the dependencies failed: Module 'DBIx::Simple::Class' is not installed, Module 'Mojolicious::Plugin::DSC' is not installed
! Bailing out the installation for Ado-0.83.
1 distribution installed

perl v5.18.2
Linux 3.13.0-44-generic #73-Ubuntu SMP

**Comment by neiromancer** [comment]
Can install only with force 
cpanm -f Mojolicious::Plugin::DSC

**Comment by kberov** [comment]
Hi @neiromancer ,
Well I can not say much about the reason why installation fails.
The reason can be found in the specific cpanm logs, which should be somewhere in ~/.cpanm folder.
May be some test failed. May be you can check what paths you have in your $PERL5LIB.

Can you check what you have in cpanm logs?

**Comment by neiromancer** [comment]
Looks like DBD::mysql is required for tests

t/01-dbix-simple-class-schema-mysql.t ... skipped: DBD::mysql is required for this test.

#   Failed test 'quits OK'
#   at t/01-dbix-simple-class-schema-sqlite.t line 161.

#   Failed test 'quits OK'
#   at t/01-dbix-simple-class-schema-sqlite.t line 189.
# Looks like you failed 2 tests of 55.
t/01-dbix-simple-class-schema-sqlite.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/55 subtests 
t/01-dbix-simple-class-sqlite.t ......... ok
t/02-dbix-simple-class-mysql.t .......... skipped: DBD::mysql is required for this test.
t/boilerplate.t ......................... ok
t/manifest.t ............................ skipped: Author tests not required for installation
t/pod-coverage.t ........................ ok
t/pod.t ................................. ok

Test Summary Report
-------------------
t/01-dbix-simple-class-schema-sqlite.t (Wstat: 512 Tests: 55 Failed: 2)
  Failed tests:  47, 54
  Non-zero exit status: 2
Files=9, Tests=193,  1 wallclock secs ( 0.07 usr  0.02 sys +  0.48 cusr  0.08 csys =  0.65 CPU)
Result: FAIL
Failed 1/9 test programs. 2/193 subtests failed.

**Comment by kberov** [comment]
@neiromancer , as you see "skipped: DBD::mysql" means only that this test would not be skipped if DBD::mysql was installed. See http://perldoc.perl.org/Test/More.html#SYNOPSIS
The failing tests are in t/01-dbix-simple-class-schema-sqlite.t 
https://github.com/kberov/DBIx--Simple--Class/blob/master/t/01-dbix-simple-class-schema-sqlite.t#L161
https://github.com/kberov/DBIx--Simple--Class/blob/master/t/01-dbix-simple-class-schema-sqlite.t#L189
Looks like a file permission issue.
you can safely ignore this if you know why there is no permission for the test scrip to chmod some file.
do:
```cpanm -n DBIx::Simple::Class```
or 
```cpanm --force DBIx::Simple::Class```
Please note that this is not an issue directly related with Ado neither DBIx::Simple::Class. it is rather related to your local setup. See http://www.cpantesters.org/distro/D/DBIx-Simple-Class.html?oncpan=1&distmat=1&version=1.008&grade=2
Please inform me if you found exactly why there are no permissions.

Thanks for the feedback.

**Comment by kberov** [comment]
Ah,  my mistake, it is not related to chmod, but to dumping the generated model classes. Still this os not observed anywhere else.
